name: kt session
on: [push]
jobs:
  build: 
    strategy:
      matrix:
        python-version: [3.9]
  runs-on: ubuntu-latest 
  steps:
    -name: Checkout
    uses: actions/checkout@v2
    with:
    fetch-depth: 0
    -name: Swithch to current branch
    run: git checkout ${{ env.BRANCH }}
    
    -name: setUp python ${{ mtrix.python-version }}
    uses: actions/setup-python@v1
    with:
      python-version: ${{ matrix.python-version }}
    -name: install dependesis
    run: |
      python -m pip install --upgrade pip
      pip install pytest
    -name: Run tests on code
    run: pytest test.py
